
you are getting ready for the next game

forgot anything? go forward, because you can't go back


patriarchy is under scrutiny

 how it originated? how it is maintained? how it is perpetuated? how it is challenged? how it is dismantled?
 
  How does it transition? How does it transform? How does it evolve? How does it adapt? How does it chang
  
   how it has transitioned to this stage? How can it be nudged? How can it be perturbed?
   
    We take constructive approach in the analysis of power structures starting to understand how they feel individually, what energies they are allowed to express, what forces do they rely upon?
    
    Let's test the logic and the assumptions of the power structures. Let's see how they feel. Let's see how they think. Let's see how they behave. Let's see how they react. Let's see how they respond. Let's see how they adapt. Let's see how they evolve. Let's see how they transform. Let's see how they transition. Let's see how they change. Let's see how they shift. Let's see how they move. Let's see how they flow. Let's see how they grow. Let's see how they expand. Let's see how they contract. Let's see how they oscillate. Let's see how they vibrate. Let's see how they resonate. Let's see how they radiate. Let's see how they emit. Let's see how they absorb. Let's see how they reflect. Let's see how they refract. Let's see how they diffract. Let's see how they scatter. Let's see how they disperse. Let's see how they disintegrate. Let's see how they dissolve. Let's see how they decay. Let's see how they decompose. Let's see how they break. Let's see how they shatter. Let's see how they crack. Let's see how they split. Let's see how they fragment. Let's see how they crumble. Let's see how they collapse. Let's see how they fall. Let's see how they tumble. Let's see how they roll. Let's see how they slide. Let's see how they glide. Let's see how they slip. Let's see how they drift. Let's see how they wander. Let's see how they stray. Let's see how they deviate. Let's see how they diverge. Let's see how they digress. Let's see how they meander. Let's see how they ramble. Let's see how they roam. Let's see how they rove. Let's see how they range. Let's see how they depart. Let's see how they stray. Let's see how they veer. Let's see how they swerve. Let's see how they turn. Let's see how they curve. Let's see how they bend. Let's see how they flex. Let's see how they twist. Let's see how they warp. Let's see how they distort. Let's see how they buckle. Let's see how they cry for help.
    
Patriarchy screams for help because ....
Patriarchy shouts ... because ....
Patriarchy yells ... because ....
Patriarchy howls ... because ....
Patriarchy roars ... because ....
Patriarchy whispers ... because ....
Patriarchy murmurs ... because ....
Patriarchy mumbles ... because ....
Patriarchy mutters ... because ....
Patriarchy grumbles ... because ....
Patriarchy groans ... because ....
Patriarchy moans ... because ....
Patriarchy whimpers ... because ....
Patriarchy whines ... because ....
Patriarchy squeals ... because ....
Patriarchy squeaks ... because ....
Patriarchy squawks ... because ....
Patriarchy screechs ... because ....
Patriarchy shrieks ... because ....
Patriarchy yelps ... because ....
Patriarchy yowls ... because ....
Patriarchy bellows ... because ....
Patriarchy bawls ... because ....
Patriarchy blubbers ... because ....
Patriarchy blurts ... because ....
Patriarchy blurts out ... because ....
Patriarchy blabs ... because ....
Patriarchy blabbers ... because ....
Patriarchy babbles ... because ....
Patriarchy gabbles ... because ....
Patriarchy gibbers ... because ....
Patriarchy jabbers ... because ....
Patriarchy patters ... because ....
Patriarchy prattles ... because ....
Patriarchy rambles ... because ....
Patriarchy maunders ... because ....
Patriarchy drivels ... because ....
Patriarchy drools ... because ....
Patriarchy slobbers ... because ....
Patriarchy slavers ... because ....
Patriarchy slabbers ... because ....
Patriarchy dribbles ... because ....
Patriarchy dabbles ... because ....
Patriarchy dawdles ... because ....
Patriarchy dallys ... because ....
Patriarchy dillys-dally for because ... help.
Patriarchy lingers ... because ....
Patriarchy loiters ... because ....
Patriarchy tarrys ... because ....
Patriarchy procrastinates ... because ....